### ISSUE TITLE
Client lighting updates are insanely expensive

### ISSUE THREAD

**Issue by hampop** [Red-Studio-Ragnarok/Alfheim#20]
## Describe the bug

***A clear and concise description of what the bug is.***

Alfheim cause more lighting lag than hesperus  

## Reproducibility
Please try to reproduce the issue with as few other mods as possible. Then check one of the following checkboxes according to your results. To check a checkbox, replace the space between the square brackets with an x (like this [x]) or create the issue and check the checkbox by clicking on it.

- [ ] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

## To Reproduce

***Steps to reproduce the behavior:***

1. Go to ''

## Screenshots or/and videos

Alfheim 
https://github.com/Red-Studio-Ragnarok/Alfheim/assets/87606666/31cbe6a3-2477-4c3e-b484-096e2251c8d3

hesperus  
https://github.com/Red-Studio-Ragnarok/Alfheim/assets/87606666/480b46a7-9495-4392-b0f7-1b53bb437507

***If applicable, add screenshots and/or videos to help explain your problem.***

## Versions

- Forge: [e.g. 1.12.2 - 14.23.5.2860]
![image](https://github.com/Red-Studio-Ragnarok/Alfheim/assets/87606666/38e79837-67b3-46c4-a006-9a3dd134c0a0)

![image](https://github.com/Red-Studio-Ragnarok/Alfheim/assets/87606666/a781c8f3-b01d-4b98-be31-af59562f935b)

## Specification:

- OS: [Windows 11]
- CPU: [Ryzen 5 5500u]
- GPU: [igpu vega 7]
- RAM Allocated: [4gb]

**Comment by Desoroxxx** [comment]
https://github.com/Red-Studio-Ragnarok/Alfheim/assets/82710983/8bf00aa1-89e3-4860-94e3-7e33498c07f6
I know what is causing this, but I have no idea why it would have such an impact on performance.
Basically, Alfheim improves client-side performance by doing lights update over time instead of doing them all at once, which create a smoother framerate, but here for whatever reason it is insanely expensive, I will look into it

**Comment by Desoroxxx** [comment]
https://github.com/Red-Studio-Ragnarok/Alfheim/assets/82710983/8bf00aa1-89e3-4860-94e3-7e33498c07f6

I know what is causing this, but I have no idea why it would have such an impact on performance.
Basically, Alfheim improves client-side performance by doing lights update over time instead of doing them all at once, which create a smoother framerate, but here for whatever reason it is insanely expensive, I will look into it

**Comment by hampop** [comment]
i have did a bit more testing and i can say the little spike after i place the glowstone was my recording software or something in the background doing that

**Comment by Desoroxxx** [comment]
Perfect
