### ISSUE TITLE
Client Lighting Not Updating

### ISSUE THREAD

**Issue by Michael-Sebero** [Red-Studio-Ragnarok/Alfheim#40]
### Describe the bug

Placing down light sources sometimes causes this issue.

![2024-02-29-08-37-56](https://github.com/Red-Studio-Ragnarok/Alfheim/assets/106393611/ffb8dc88-e40f-442e-aa52-51f4f1d908f3)

![2024-02-29_08 40 25](https://github.com/Red-Studio-Ragnarok/Alfheim/assets/106393611/1d6e969e-f3e4-4f98-aff3-6421b4063c21)

### Reproducibility

- [X] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

### Screenshots and/or videos

Attached

### Logs

NA

### Debug Logs

NA

### Crash Reports

NA

### Alfheim Version

1.2

### Forge Version

1.12.2 - 14.23.5.2860

### MixinBooter Version

9.1

### Java Version

8

### Java Virtual Machine

Hotspot

### Operating System

Linux

### GPU Vendor

NVIDIA

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by XvaleX10** [comment]
![2024-03-11_20 55 56](https://github.com/Red-Studio-Ragnarok/Alfheim/assets/129081719/9b4d794b-9bb3-4ee8-96e2-29fd41482680)
Same issue

> ### Describe the bug
> Placing down light sources sometimes causes this issue.
> 
> ![2024-02-29-08-37-56](https://private-user-images.githubusercontent.com/106393611/309041272-ffb8dc88-e40f-442e-aa52-51f4f1d908f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxODcyNzUsIm5iZiI6MTcxMDE4Njk3NSwicGF0aCI6Ii8xMDYzOTM2MTEvMzA5MDQxMjcyLWZmYjhkYzg4LWU0MGYtNDQyZS1hYTUyLTUxZjRmMWQ5MDhmMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMVQxOTU2MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MGE5MzJjNmY2MzdmMWQyNTZkNTg1MWJhYmRlZTY1MTgwOTA2OTBmZjAyZGE4YjU4Yzg0OWUzZTg3YTE5Y2JmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0OlM6rRfQonkXeJpTM1B4sM4LhgLTttnJq607SfH21g)
> 
> ![2024-02-29_08 40 25](https://private-user-images.githubusercontent.com/106393611/309040621-1d6e969e-f3e4-4f98-aff3-6421b4063c21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxODcyNzUsIm5iZiI6MTcxMDE4Njk3NSwicGF0aCI6Ii8xMDYzOTM2MTEvMzA5MDQwNjIxLTFkNmU5NjllLWYzZTQtNGY5OC1hZmYzLTY0MjFiNDA2M2MyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMVQxOTU2MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNzBhZTk4MTYzYjRjZWM0ZWFiNmFmMTgzZmQxNTU4ZTNkODg3OTI5MzM5MWU2ZGI5NWJmMDdjOTk2OGQ0M2E1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aEz8a-eHfInS5WHMboUiM2PMNGfvrThv4tuYvKTXP-Q)
> 
> ### Reproducibility
> * [x]  I reproduced this issue with as few other mods as possible installed.
> * [ ]  I am unable to reproduce this issue consistently.
> 
> ### Screenshots and/or videos
> Attached
> 
> ### Logs
> NA
> 
> ### Debug Logs
> NA
> 
> ### Crash Reports
> NA
> 
> ### Alfheim Version
> 1.2
> 
> ### Forge Version
> 1.12.2 - 14.23.5.2860
> 
> ### MixinBooter Version
> 9.1
> 
> ### Java Version
> 8
> 
> ### Java Virtual Machine
> Hotspot
> 
> ### Operating System
> Linux
> 
> ### GPU Vendor
> NVIDIA
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct

**Comment by Desoroxxx** [comment]
> ![2024-03-11_20 55 56](https://private-user-images.githubusercontent.com/129081719/311849662-9b4d794b-9bb3-4ee8-96e2-29fd41482680.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwNDE2MjYsIm5iZiI6MTcxMTA0MTMyNiwicGF0aCI6Ii8xMjkwODE3MTkvMzExODQ5NjYyLTliNGQ3OTRiLTliYjMtNGVlOC05NmUyLTI5ZmQ0MTQ4MjY4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMVQxNzE1MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZWE2YTg1ODZmYzQzZTIwNDYwNjAyZWI0MTU1NTgxMDNlM2QxNWZmNWM2MzBkNWQ3OWYxNzQxMTk3ZDU3ZDkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.10SLeTx8mt1UaYlPtClja-Am4v8MdtagUuG0OoB29tY) Same issue

Where you using Vintagium?

**Comment by XvaleX10** [comment]
> > ![2024-03-11_20 55 56](https://private-user-images.githubusercontent.com/129081719/311849662-9b4d794b-9bb3-4ee8-96e2-29fd41482680.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwNDE2MjYsIm5iZiI6MTcxMTA0MTMyNiwicGF0aCI6Ii8xMjkwODE3MTkvMzExODQ5NjYyLTliNGQ3OTRiLTliYjMtNGVlOC05NmUyLTI5ZmQ0MTQ4MjY4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMVQxNzE1MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZWE2YTg1ODZmYzQzZTIwNDYwNjAyZWI0MTU1NTgxMDNlM2QxNWZmNWM2MzBkNWQ3OWYxNzQxMTk3ZDU3ZDkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.10SLeTx8mt1UaYlPtClja-Am4v8MdtagUuG0OoB29tY) Same issue
> 
> Where you using Vintagium?

no

**Comment by Desoroxxx** [comment]
> no

Could you send logs?

**Comment by XvaleX10** [comment]
> > no
> 
> Could you send logs?

Unfortunately not, I deleted the modpack a week ago

**Comment by nyan-mining** [comment]
I was able to reproduce this issue, if there is no air block in range in an adjacent chunk to a newly placed light source that can be updated, the light for solid blocks do not update. 
Using Alfheim 1.3 and Vintagium.

Placing a torch near a chunk border where the adjacent chunk has no air block to update:
![2024-05-16_17 18 14](https://github.com/Red-Studio-Ragnarok/Alfheim/assets/166334723/49ed61d0-b252-4b94-94d6-171d723bb736)

Creating an air block in the adjacent chunk (chunk will update because I broke a block):
![2024-05-16_17 18 26](https://github.com/Red-Studio-Ragnarok/Alfheim/assets/166334723/7b3f0fb9-3f7b-43bc-bb89-9237dc8f5ef6)

Removing the light source:
![2024-05-16_17 18 32](https://github.com/Red-Studio-Ragnarok/Alfheim/assets/166334723/111c244a-499e-4008-8be1-6a2062ba345b)

Replacing the light source, the adjacent chunk updates because there is an air block to update!
![2024-05-16_17 18 38](https://github.com/Red-Studio-Ragnarok/Alfheim/assets/166334723/f8349cb8-3e28-4b7a-bcd5-1839e3987919)

If I fill in the block and remove the torch, there is no longer an air block to update and the blocks light do not change:
![2024-05-16_18 07 50](https://github.com/Red-Studio-Ragnarok/Alfheim/assets/166334723/8e0a5ef4-2d04-4b63-8776-f36c537a3201)

Y-axis example in a superflat world where the player's feet are at Y 64 (grass blocks are Y 63):
![2024-05-16_18 21 08](https://github.com/Red-Studio-Ragnarok/Alfheim/assets/166334723/5a89e231-05fe-4f73-9f37-94856f566816)

Removing the torch, creating air blocks in the adjacent chunks, and then replacing the torch:
![2024-05-16_18 21 23](https://github.com/Red-Studio-Ragnarok/Alfheim/assets/166334723/4dea7716-63bc-484f-bcbb-8b9b80f53d2a)

**Comment by Whitebrim** [comment]
Still exsist on 1.4
![image](https://github.com/Red-Studio-Ragnarok/Alfheim/assets/23287829/9c5cb47f-3223-4110-85d4-b47021f0ad09)

**Comment by Desoroxxx** [comment]
Could any of you try with the latest Alfheim 1.4?

**Comment by JohanniklasLp** [comment]
Alfheim 1.4 in an otherwise vanilla instance.
It seems fine across chunk borders, but not across the corner.
![lighting](https://github.com/user-attachments/assets/92c63e79-90fc-447d-810f-6fd1c9f44334)

Placing a torch adjacent to the wall made it light up, but now it's glowing
![2024-08-23_17 06 18](https://github.com/user-attachments/assets/eeb64cf5-eaa4-4654-8f29-1eeb345cfbda)
![2024-08-23_17 04 04](https://github.com/user-attachments/assets/cdd6b0cf-1722-4eed-ad38-958b2a14de17)

Placing the torch again and breaking it after a bit more time made the wall dark again, returning to the picture 1 behaviour



Testing with another wall, it broke across chunk borders again
![grafik](https://github.com/user-attachments/assets/a61afbf0-d80f-465e-9813-a22cae0282ab)

**Comment by MagmaBro123** [comment]
I've noticed this issue as well.

**Comment by beltxd** [comment]
Are there any updates to this issue and any underlying causes? I have the same issue as well with the lighting.

**Comment by darchitectlp** [comment]
Also seeing this issue in Roguelike Adventures and Dungeons modpack (which uses Alfheim-1.4.jar). Would be lovely to have a fix. I'm also playing Dimension Hopper modpack which uses Alfheim-1.4-Dev-1.jar, and I don't see the same lighting glitches. Not sure if that helps.

**Comment by erialsan** [comment]
This problem remains unresolved.

**Comment by Desoroxxx** [comment]
Yeah this is quite annoying to me, I have barely any info on this, and it seems to rarely happen all things considered which make this harder.

I will try to see if I can spot any changes that could cause this next update, but I cannot promise to find a definite fix.

**Comment by erialsan** [comment]
![image](https://github.com/user-attachments/assets/231806cf-a8a9-4fbb-ae66-07f0e03f5d06)
It can almost certainly be generated with Quark RotN's Torch bow.

**Comment by xskutsu** [comment]
I'm having the same issue as well. interestingly it only seems to occur when the forge setting "Force threaded chunk rendering" is enabled. (Minecraft Forge -> Client Settings -> Force Threaded Chunk Rendering)
